cmake_minimum_required(VERSION 3.16)
find_package(ASC REQUIRED HINTS $ENV{ASCEND_INSTALL_PATH}/compiler/tikcpp/ascendc_kernel_cmake)
project(kernel_samples LANGUAGES ASC CXX)
add_executable(matmul_16_32_16 matmul.asc)
target_link_libraries(matmul_16_32_16 PRIVATE tiling_api register platform m dl)
target_compile_options(matmul_16_32_16 PRIVATE $<$<COMPILE_LANGUAGE:ASC>:--npu-arch=dav-3510>)
